### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by scottpchow23** [Georgetown-IR-Lab/OpenNIR#29]
Hey Sean!

Finally got the docker configuration running on my HPC but I might be doing something wrong because despite the pipeline detecting the gpus, I'm consistently getting an out of memory error from CUDA when I try to train using `scripts/pipeline.sh config/cedr/knrm config/robust/fold1`:

```
[2020-11-17 17:01:24,584][onir.interfaces.java][DEBUG] [starting] initializing jnius
[2020-11-17 17:01:25,643][onir.interfaces.java][DEBUG] [finished] initializing jnius [1.06s]
[2020-11-17 17:01:28,874][onir][CRITICAL] Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/schow/OpenNIR/onir/bin/pipeline.py", line 21, in <module>
    main()
  File "/home/schow/OpenNIR/onir/bin/pipeline.py", line 17, in main
    context['pipeline'].run()
  File "/home/schow/OpenNIR/onir/pipelines/default.py", line 54, in run
    for train_ctxt in self.trainer.iter_train(only_cached=self.config['only_cached']):
  File "/home/schow/OpenNIR/onir/trainers/base.py", line 114, in iter_train
    train_batch_result = self.train_batch()
  File "/home/schow/OpenNIR/onir/trainers/pairwise.py", line 81, in train_batch
    rel_scores = self.ranker(**input_data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/schow/OpenNIR/onir/rankers/base.py", line 44, in forward
    result = self._forward(**inputs)
  File "/home/schow/OpenNIR/onir/rankers/cedr_knrm.py", line 23, in _forward
    rep = self.encoder.enc_query_doc(**inputs)
  File "/home/schow/OpenNIR/onir/vocab/bert_vocab.py", line 196, in enc_query_doc
    result = self.bert(toks, segment_ids, mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/schow/OpenNIR/onir/modules/bert.py", line 11, in forward
    return self.bert(input_ids, token_type_ids, attention_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/schow/OpenNIR/onir/modules/bert.py", line 50, in forward
    return self.forward_from_layer(embedding_output, attention_mask)
  File "/home/schow/OpenNIR/onir/modules/bert.py", line 58, in forward_from_layer
    _, encoded_layers = self.encoder(embedding_output, extended_attention_mask, head_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_bert.py", line 437, in forward
    layer_outputs = layer_module(hidden_states, attention_mask, head_mask[i])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_bert.py", line 415, in forward
    attention_outputs = self.attention(hidden_states, attention_mask, head_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_bert.py", line 372, in forward
    self_outputs = self.self(input_tensor, attention_mask, head_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_bert.py", line 309, in forward
    attention_scores = attention_scores / math.sqrt(self.attention_head_size)
RuntimeError: CUDA out of memory. Tried to allocate 190.00 MiB (GPU 0; 15.90 GiB total capacity; 14.77 GiB already allocated; 57.38 MiB free; 383.33 MiB cached)
```

I imagine it's something along the lines of lowering the batch size for training but I'm not sure where to make that change.

Any thoughts?

**Comment by seanmacavaney** [comment]
Hey Scott,

Try setting `trainer.grad_acc_batch=1` -- this is the "gradient accumulation" batch size. If that's not enough, you can try lowering the maximum document length using `ranker.dlen=500` (or another length), though of course chopping off more content isn't ideal. (These are command line arguments you can add.)

 \- sean

**Comment by scottpchow23** [comment]
That seems to have done it! Thanks for the save as usual.
