### ISSUE TITLE
problem when initialize the MSMARCO data

### ISSUE THREAD

**Issue by KaishuaiXu** [Georgetown-IR-Lab/OpenNIR#31]
when I initialize the MSMARCO data, this problem appears.

> [2021-01-20 11:49:37,205][dataset:msmarco][DEBUG] [starting] documents                                              
[2021-01-20 12:08:47,518][dataset:msmarco][DEBUG] [finished] documents: [19:10] [8841823it] [7686.45it/s]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/kaishuai/OpenNIR/onir/util/concurrency.py", line 53, in _blocking_tee_iter
    raise ctrl.ex
  File "/home/kaishuai/OpenNIR/onir/util/concurrency.py", line 53, in _blocking_tee_iter
    raise ctrl.ex
  File "/home/kaishuai/OpenNIR/onir/util/concurrency.py", line 77, in run
    self.value = next(self._it)
StopIteration
The above exception was the direct cause of the following exception:
Exception in thread Thread-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/kaishuai/OpenNIR/onir/util/concurrency.py", line 53, in _blocking_tee_iter
  File "/home/kaishuai/anaconda3/envs/epic/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    raise ctrl.ex
  File "/home/kaishuai/OpenNIR/onir/util/concurrency.py", line 53, in _blocking_tee_iter
    self.run()
    raise ctrl.ex
  File "/home/kaishuai/anaconda3/envs/epic/lib/python3.8/threading.py", line 870, in run
  File "/home/kaishuai/OpenNIR/onir/util/concurrency.py", line 77, in run
    self.value = next(self._it)
StopIteration
The above exception was the direct cause of the following exception:
    self._target(*self._args, **self._kwargs)
  File "/home/kaishuai/OpenNIR/onir/indices/sqlite.py", line 37, in build
Traceback (most recent call last):
  File "/home/kaishuai/anaconda3/envs/epic/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    for doc in documents:
RuntimeError: generator raised StopIteration
    self.run()
  File "/home/kaishuai/anaconda3/envs/epic/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kaishuai/OpenNIR/onir/indices/anserini.py", line 304, in build
    for i, doc in enumerate(doc_iter):
RuntimeError: generator raised StopIteration

**Comment by seanmacavaney** [comment]
It looks like behavior changed between Python 3.7 and 3.7 that disallows generator functions from raising StopIteration: https://docs.python.org/3/whatsnew/3.7.html#changes-in-python-behavior

I'll have to fix this, but a temporary workaround will be using python 3.7 instead for the time being.

**Comment by KaishuaiXu** [comment]
Thanks a lot for your reply, I solve it by creating another env with python==3.6.9. :)
